name: CI
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - stable-*
  workflow_dispatch:

jobs:
  linters:
    uses: ./.github/workflows/linters.yml # use the callable linters job to run tests
  changelog:
    uses: ansible/ansible-content-actions/.github/workflows/changelog.yaml@main
    if: github.event_name == 'pull_request'
  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@main
  units:
    uses: ansible-network/github_actions/.github/workflows/unit_source.yml@main

  all_green:
    if: ${{ always() }}
    needs:
      - linters
      - changelog
      - sanity
      - units
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert 'failure' not in
          set([
          '${{ needs.linters.result }}',
          '${{ needs.changelog.result }}',
          '${{ needs.sanity.result }}',
          '${{ needs.units.result }}'
          ])"
